default:
  ce_gap: '25'
  ce_quantity: 75
  ce_reset_gap: 30
  ce_start_point: 0
  ce_symbol_gap: 200
  exchange: NFO
  index_symbol: NSE:NIFTY 50
  min_price_to_sell: 15
  order_type: MARKET
  pe_gap: '30'
  pe_quantity: 75
  pe_reset_gap: 30
  pe_start_point: 0
  pe_symbol_gap: 200
  product_type: NRML
  sell_multiplier_threshold: 5
  symbol_initials: NIFTY25807
  trans_type: SELL
